services:
  url-shortener:
    build: .
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      # Эта переменная переопределит значение DB_HOST из .env файла
      # специально для этого контейнера.
      - DB_HOST=db
    volumes:
      - ./.env:/url-shortener/.env
    depends_on:
      db:
        condition: service_healthy
    command: ["./entrypoint.sh"]
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data: